/**
 * ONLY ADMINS, USE projects.ts to list your project.
 */

export const FEATURED_PROJECTS = [
  {
    color: '#5F224A',
    logo: 'longhorn.svg',
    tag: 'storage',
    name: 'Longhorn',
    description: 'Cloud-Native distributed block storage built on and for Kubernetes.',
    href: 'https://longhorn.io/',
    repositoryURL: 'https://github.com/longhorn/longhorn',
    twitterURL: '',
    documentationURL: '',
  },
  {
    color: '#0280BE',
    logo: 'rancher-desktop.svg',
    tag: 'development',
    name: 'Rancher Desktop',
    description: 'Kubernetes on your desktop.',
    href: 'https://rancherdesktop.io/',
    repositoryURL: 'https://github.com/rancher-sandbox/rd',
    twitterURL: '',
    documentationURL: '',
  },
  {
    color: '#05A480',
    logo: 'harvester.svg',
    tag: 'infrastructure',
    name: 'Harvester',
    description: 'Open source hyperconverged infrastructure (HCI) software.',
    href: 'https://harvesterhci.io/',
    repositoryURL: 'https://github.com/rancher/harvester',
    twitterURL: '',
    documentationURL: '',
  },
  {
    color: '#28BBBF',
    logo: 'uyuni.svg',
    tag: 'operation',
    name: 'Uyuni',
    description: 'The best tool to deploy and manage your enterprise Linux infrastructure, powered by Salt and Ansible',
    href: 'https://www.uyuni-project.org',
    repositoryURL: 'https://github.com/uyuni-project/uyuni',
    twitterURL: 'https://twitter.com/UyuniProject',
    documentationURL: '',
  },
  {
    color: '#D13207',
    logo: 'neuvector.png',
    tag: 'security',
    name: 'NeuVector',
    description: 'NeuVector delivers Full Lifecycle Container Security',
    href: 'https://neuvector.com/products/open-source/',
    repositoryURL: 'https://github.com/neuvector',
    twitterURL: '',
    documentationURL: 'https://open-docs.neuvector.com/',
  },
  {
    color: '#BB2A46',
    logo: 'kubewarden.png',
    tag: 'infrastructure',
    name: 'Kubewarden',
    description: 'Kubernetes admission control using WebAssembly (WASM).',
    href: 'https://kubewarden.io/',
    repositoryURL: 'https://github.com/kubewarden',
    twitterURL: 'https://twitter.com/kubewarden',
    documentationURL: '',
  },
  {
    color: '#045209',
    logo: 'sle_bci.png',
    tag: 'development',
    name: 'SLE BCI',
    description: 'SUSE maintained containers that are redistributable, open source, secure and dependable.',
    href: 'https://registry.suse.com/',
    repositoryURL: 'https://github.com/SUSE/BCI-dockerfile-generator',
    twitterURL: '',
    documentationURL: 'https://opensource.suse.com/bci-docs/',
  },
  {
    color: '#83D6AE',
    logo: 'trento.svg',
    tag: 'infrastructure',
    name: 'Trento',
    description: 'An open cloud-native web console to manage OS-related tasks for SAP applications.',
    href: 'https://www.trento-project.io/',
    repositoryURL: 'https://github.com/trento-project',
    twitterURL: '',
    documentationURL: '',
  },
  {
    color: '#83D6AE',
    logo: 'k3s.svg',
    tag: 'infrastructure',
    name: 'K3s',
    description: 'K3s is a fully compliant and certified Kubernetes distribution built for IoT & Edge computing',
    href: 'https://k3s.io/',
    repositoryURL: 'https://github.com/k3s-io/k3s',
    twitterURL: '',
    documentationURL: 'https://docs.k3s.io/',
  },
]
