
export interface ProjectT {
  [key: string]: string
}

export const PROJECTS = [
  {
    isEnable: true,
    tag: 'operations',
    name: 'aliyun-img-utils',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/aliyun-img-utils',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'Auarium',
    description: '',
    repositoryURL: 'github.com/aquarist-labs/aquarium',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'AutoK3s',
    description: '',
    repositoryURL: 'github.com/cnrancher/autok3s',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'azuremetadata',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/azuremetadata',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'blue-horizon',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/blue-horizon',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'Cavil',
    description: '',
    repositoryURL: 'github.com/openSUSE/cavil',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Combustion',
    description: '',
    repositoryURL: 'en.opensuse.org/Portal:MicroOS/Combustion',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'security',
    name: 'ComplianceAsCode',
    description: '',
    repositoryURL: 'github.com/SUSE/ComplianceAsCodeContent/',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'cscreen',
    description: '',
    repositoryURL: 'github.com/openSUSE/cscreen',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'ec2metadata',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/ec2metadata',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'ec2imgutils',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/ec2imgutils	',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'Epinio',
    description: '',
    repositoryURL: 'epinio.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Fleet',
    description: '',
    repositoryURL: 'fleet.rancher.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'ai/ml',
    name: 'FuseML',
    description: '',
    repositoryURL: 'fuseml.github.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'gcemetadata',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/gcemetadata',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'gceimgutils',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/gceimgutils	',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'gfxboot',
    description: '',
    repositoryURL: 'github.com/openSUSE/gfxboot',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'infrastructure',
    name: 'Harvester',
    description: '',
    repositoryURL: 'harvesterhci.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'education',
    name: 'HobbyFarm',
    description: '',
    repositoryURL: 'github.com/hobbyfarm',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'hwinfo',
    description: '',
    repositoryURL: 'github.com/openSUSE/hwinfo',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Hypper',
    description: '',
    repositoryURL: 'hypper.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'img-proof',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/img-proof',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'infrastructure',
    name: 'Jangouts',
    description: '',
    repositoryURL: 'github.com/jangouts/jangouts#readme',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'jeos-firstboot',
    description: '',
    repositoryURL: 'github.com/openSUSE/jeos-firstboot',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'jeos-firstboot',
    description: '',
    repositoryURL: 'github.com/openSUSE/jeos-firstboot',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'K3OS',
    description: '',
    repositoryURL: 'k3os.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'kubernetes',
    name: 'K3S',
    description: '',
    repositoryURL: 'k3s.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'kanku',
    description: '',
    repositoryURL: 'm0ses.github.io/kanku',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'keg',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/keg',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'kubernetes',
    name: 'kim',
    description: '',
    repositoryURL: 'github.com/rancher/kim',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'kiwi',
    description: '',
    repositoryURL: 'github.com/OSInside/kiwi',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'klp-ccp',
    description: '',
    repositoryURL: 'github.com/SUSE/klp-ccp',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'security',
    name: 'Kubewarden',
    description: '',
    repositoryURL: 'kubewarden.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'Kubic',
    description: '',
    repositoryURL: 'kubic.opensuse.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'security',
    name: 'kucero',
    description: '',
    repositoryURL: 'github.com/SUSE/kucero',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'libeconf',
    description: '',
    repositoryURL: 'github.com/openSUSE/libeconf',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'libpulp',
    description: '',
    repositoryURL: 'github.com/SUSE/libpulp',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'libsolv',
    description: '',
    repositoryURL: 'https://en.opensuse.org/openSUSE:Libzypp_satsolver',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'libstorage-ng',
    description: '',
    repositoryURL: 'yast.opensuse.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'Longhorn',
    description: '',
    repositoryURL: 'longhorn.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'Longhorn',
    description: '',
    repositoryURL: 'longhorn.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'mash',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/mash',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'mash-client',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/mash-client',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'MirrorCache',
    description: '',
    repositoryURL: 'github.com/openSUSE/MirrorCache',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'obsgit',
    description: '',
    repositoryURL: 'github.com/openSUSE/obsgit',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'Open Build Service',
    description: '',
    repositoryURL: 'openbuildservice.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'Open Build Service Connector',
    description: '',
    repositoryURL: 'marketplace.visualstudio.com/items?itemName=SUSE.open-build-service-connector',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'openQA',
    description: '',
    repositoryURL: 'open.qa',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'openSUSE Leap',
    description: '',
    repositoryURL: 'en.opensuse.org/Portal:Distribution',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'openSUSE MicroOS',
    description: '',
    repositoryURL: 'microos.opensuse.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'openSUSE Tumbleweed',
    description: '',
    repositoryURL: 'en.opensuse.org/Portal:Tumbleweed',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Opni',
    description: '',
    repositoryURL: 'opni.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'ai/ml',
    name: 'Phoebe',
    description: '',
    repositoryURL: 'github.com/SUSE/phoebe/wiki',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'infrastructure',
    name: 'public-cloud-info-service',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/public-cloud-info-service',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'networking',
    name: 'Prometheus Webhook SNMP',
    description: '',
    repositoryURL: 'github.com/SUSE/prometheus-webhook-snmp',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Rancher',
    description: '',
    repositoryURL: 'rancher.com',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Rancher Desktop',
    description: '',
    repositoryURL: 'rancherdesktop.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'Rio',
    description: '',
    repositoryURL: 'rio.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'kubernetes',
    name: 'RKE',
    description: '',
    repositoryURL: 'rancher.com/products/rke',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'kubernetes',
    name: 'RKE Government',
    description: '',
    repositoryURL: 'docs.rke2.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Repository Mirroring Tool (RMT)',
    description: '',
    repositoryURL: 'github.com/SUSE/rmt',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'service-access-config',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/service-access-config',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Snapper',
    description: '',
    repositoryURL: 'snapper.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'networking',
    name: 'Submariner',
    description: '',
    repositoryURL: 'submariner.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'supportutils',
    description: '',
    repositoryURL: 'github.com/openSUSE/supportutils',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'transactional-update',
    description: '',
    repositoryURL: 'microos.opensuse.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Trento',
    description: '',
    repositoryURL: 'trento-project.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Uyuni',
    description: '',
    repositoryURL: 'uyuni-project.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'venvjail',
    description: '',
    repositoryURL: 'github.com/openSUSE/venvjail',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'infrastructure',
    name: 'vhostmd',
    description: '',
    repositoryURL: 'github.com/vhostmd/vhostmd',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'RKE Cluster Linter for VS Code',
    description: '',
    repositoryURL: 'marketplace.visualstudio.com/items?itemName=dancermak.vscode-rke-cluster-config',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'networking',
    name: 'wicked',
    description: '',
    repositoryURL: 'en.opensuse.org/Portal:Wicked',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'kubernetes',
    name: 'wins',
    description: '',
    repositoryURL: 'github.com/rancher/wins',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Yomi',
    description: '',
    repositoryURL: 'github.com/openSUSE/yomi',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Zypper',
    description: '',
    repositoryURL: 'en.opensuse.org/Portal:Zypper',
    documentationURL: '',
  },

]

// Dynamicly generated tags
const _tags = PROJECTS.map(ele => ele.tag)
export const CATEGORIES = [...new Set(_tags)]
