
export interface ProjectT {
  [key: string]: string
}

export const PROJECTS = [
  {
    isEnable: true,
    tag: 'operations',
    name: 'aliyun-img-utils',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/aliyun-img-utils',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'Auarium',
    description: '',
    repositoryURL: 'github.com/aquarist-labs/aquarium',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'AutoK3s',
    description: '',
    repositoryURL: 'github.com/cnrancher/autok3s',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'azuremetadata',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/azuremetadata',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'blue-horizon',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/blue-horizon',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'Cavil',
    description: '',
    repositoryURL: 'github.com/openSUSE/cavil',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Combustion',
    description: '',
    repositoryURL: 'en.opensuse.org/Portal:MicroOS/Combustion',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'security',
    name: 'ComplianceAsCode',
    description: '',
    repositoryURL: 'github.com/SUSE/ComplianceAsCodeContent/',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'cscreen',
    description: '',
    repositoryURL: 'github.com/openSUSE/cscreen',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'ec2metadata',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/ec2metadata',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'ec2imgutils',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/ec2imgutils	',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'Epinio',
    description: '',
    repositoryURL: 'epinio.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Fleet',
    description: '',
    repositoryURL: 'fleet.rancher.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'ai/ml',
    name: 'FuseML',
    description: '',
    repositoryURL: 'fuseml.github.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'gcemetadata',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/gcemetadata',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'gceimgutils',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/gceimgutils	',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'gfxboot',
    description: '',
    repositoryURL: 'github.com/openSUSE/gfxboot',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'infrastructure',
    name: 'Harvester',
    description: '',
    repositoryURL: 'harvesterhci.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'education',
    name: 'HobbyFarm',
    description: '',
    repositoryURL: 'github.com/hobbyfarm',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'hwinfo',
    description: '',
    repositoryURL: 'github.com/openSUSE/hwinfo',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operations',
    name: 'Hypper',
    description: '',
    repositoryURL: 'hypper.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'img-proof',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/img-proof',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'infrastructure',
    name: 'Jangouts',
    description: '',
    repositoryURL: 'github.com/jangouts/jangouts#readme',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'jeos-firstboot',
    description: '',
    repositoryURL: 'github.com/openSUSE/jeos-firstboot',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'jeos-firstboot',
    description: '',
    repositoryURL: 'github.com/openSUSE/jeos-firstboot',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'K3OS',
    description: '',
    repositoryURL: 'k3os.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'kubernetes',
    name: 'K3S',
    description: '',
    repositoryURL: 'k3s.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'kanku',
    description: '',
    repositoryURL: 'm0ses.github.io/kanku',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'keg',
    description: '',
    repositoryURL: 'github.com/SUSE-Enceladus/keg',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'kubernetes',
    name: 'kim',
    description: '',
    repositoryURL: 'github.com/rancher/kim',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'kiwi',
    description: '',
    repositoryURL: 'github.com/OSInside/kiwi',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'klp-ccp',
    description: '',
    repositoryURL: 'github.com/SUSE/klp-ccp',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'security',
    name: 'Kubewarden',
    description: '',
    repositoryURL: 'kubewarden.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'operating-systems',
    name: 'Kubic',
    description: '',
    repositoryURL: 'kubic.opensuse.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'security',
    name: 'kucero',
    description: '',
    repositoryURL: 'github.com/SUSE/kucero',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'libeconf',
    description: '',
    repositoryURL: 'github.com/openSUSE/libeconf',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'libpulp',
    description: '',
    repositoryURL: 'github.com/SUSE/libpulp',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'development',
    name: 'libsolv',
    description: '',
    repositoryURL: 'https://en.opensuse.org/openSUSE:Libzypp_satsolver',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'libstorage-ng',
    description: '',
    repositoryURL: 'yast.opensuse.org',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'Longhorn',
    description: '',
    repositoryURL: 'longhorn.io',
    documentationURL: '',
  },
  {
    isEnable: true,
    tag: 'storage',
    name: 'Longhorn',
    description: '',
    repositoryURL: 'longhorn.io',
    documentationURL: '',
  },

]

// Dynamicly generated tags
const _tags = PROJECTS.map(ele => ele.tag)
export const CATEGORIES = [...new Set(_tags)]
