export const sponsored = [
  {
    isEnable: true,
    tag: 'Cloud-Native',
    name: 'CNCF',
    description: 'Enables Kubernetes and other cloud native technologies',
    repositoryURL: 'https://cncf.io/',
    documentationURL: '#',
    img: 'cncf-color.svg',
  },
  {
    isEnable: true,
    description: 'Advancing Open Source Safety-Critical Systems',
    tag: 'Edge',
    name: 'ELISA',
    repositoryURL: 'https://elisa.tech/ ',
    documentationURL: '',
    img: 'logo_elisa.png',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'O-RAN',
    description: 'Transforming the Radio Access Network industry to open, intelligent, virtualized and fully interoperable RAN.',
    repositoryURL: 'https://o-ran.org/ ',
    documentationURL: '',
    img: 'oran.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Confidential Computing',
    description: 'Data protection and trust with a strong commitment to preserving data integrity from core to cloud to edge',
    repositoryURL: 'https://confidentialcomputing.io/',
    documentationURL: '',
    img: 'cc_consortium_color.svg',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'SOAFEE',
    description: 'Delivering a cloud-native architecture for mixed-criticality automotive applications.',
    repositoryURL: 'https://soafee.io/ ',
    documentationURL: '',
    img: 'soafee.svg',
  },
  {
    isEnable: true,
    tag: 'Umbrella',
    name: 'Linux Foundation Europe',
    description: 'Trusted hub to develop, manage, and scale open technology projects globally',
    repositoryURL: 'https://linuxfoundation.eu/',
    documentationURL: '',
    img: 'LF_Logo_White.svg',
  },
  {
    isEnable: true,
    tag: 'Umbrella',
    name: 'Linux Foundation',
    description: 'Linux Foundation',
    repositoryURL: 'https://www.linuxfoundation.org/',
    documentationURL: '',
    img: 'LF_Logo_White.svg',
  },
  {
    isEnable: true,
    tag: 'Umbrella',
    name: 'GAIA-X',
    description: 'Gaia-X, initiated by Europe business politics, and science to create a federated and secure data infrastructure.',
    repositoryURL: 'https://gaia-x.eu/',
    documentationURL: '',
    img: 'Gaia-X_Logo_svg_resized_1.svg',
  },
  {
    isEnable: true,
    tag: 'Umbrella',
    name: 'margo',
    description: 'Margo',
    repositoryURL: 'https://margo.org',
    documentationURL: '',
    img: 'margo_secondary_black.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Gnome Project',
    description: 'The Gnome Project',
    repositoryURL: 'https://www.gnome.org/',
    documentationURL: '',
    img: 'gnome-logo.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'KDE Project',
    description: 'The KDE Project',
    repositoryURL: 'https://www.kde.org/',
    documentationURL: '',
    img: 'kde-logo.png',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'Nephio',
    description: 'Cloud Native Network Automation',
    repositoryURL: 'https://nephio.org/',
    documentationURL: '',
    img: 'Nephio_logo_colorblack_horizontal.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'NVM Express',
    description: 'An open collection of standards and information to expose the benefits of non-volatile memory',
    repositoryURL: 'https://nvmexpress.org/',
    documentationURL: '',
    img: 'nvm-express-web.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'OpenELA',
    description: 'Providing a secure, transparent, and reliable Enterprise Linux source',
    repositoryURL: 'https://www.OpenELA.org/',
    documentationURL: '',
    img: 'OpenELA_logo.png',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'Sylva',
    description: 'A cloud software framework tailored for telco and edge requirements',
    repositoryURL: 'https://sylvaproject.org/',
    documentationURL: '',
    img: 'sylva-logo-color.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Open Mainframe Project',
    description: 'Host of open source projects for the mainframe.',
    repositoryURL: 'https://www.openmainframeproject.org/',
    documentationURL: '',
    img: 'logo_openmainframe.png',
  },
  {
    isEnable: false,
    tag: 'Infrastructure',
    name: 'openMP',
    description: 'API for multi-platform shared-memory parallel programming',
    repositoryURL: 'https://www.openmp.org/',
    documentationURL: '',
    img: 'openmp-header-logo-100h.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'openSSF',
    description: 'Open Source Security Foundation',
    repositoryURL: 'https://openssf.org/',
    documentationURL: '',
    img: 'openssf_white.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Open Source Business Alliance',
    description: 'Open Source Business Alliance developing, building and using open source software.',
    repositoryURL: 'https://osb-alliance.de/',
    documentationURL: '',
    img: 'osba-logo-claim.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'PCI-SIG',
    description: 'Peripheral Component Interconnect SIG responsible for specifying the PCI-X and PCI Express computer buses.',
    repositoryURL: 'https://pcisig.com/',
    documentationURL: '',
    img: 'pcisig.webp',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'The Open Group O-PAS Forum',
    description: ' an open, interoperable, and secure architecture for industrial process automation systems,',
    repositoryURL: 'https://www.opengroup.org/forum/open-process-automation-forum',
    documentationURL: '',
    img: 'ogforum-opas.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'UEFI',
    description: 'Unified Extensible Firmware Interface Forum',
    repositoryURL: 'https://uefi.org/',
    documentationURL: '',
    img: 'uefi_logo_red_web.png',
  },
]
