export const sponsored = [
  {
    isEnable: true,
    tag: 'Cloud-Native',
    name: 'CNCF',
    description: 'Enables Kubernetes and other cloud native technologies',
    repositoryURL: 'https://cncf.io/',
    documentationURL: '#',
    img: 'cncf-color.svg',
  },
  {
    isEnable: true,
    description: 'Advancing Open Source Safety-Critical Systems',
    tag: 'Edge',
    name: 'ELISA',
    repositoryURL: 'https://elisa.tech/ ',
    documentationURL: '',
    img: 'logo_elisa.png',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'O-RAN',
    description: 'Transforming the Radio Access Network industry to open, intelligent, virtualized and fully interoperable RAN.',
    repositoryURL: 'https://o-ran.org/ ',
    documentationURL: '',
    img: 'oran.svg',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'Eclipse SDV',
    description: 'An open technology plaform for the Software Defined Vehicle of the future.',
    repositoryURL: 'https://sdv.eclipse.org/',
    documentationURL: '',
    img: 'eclipse-foundation-logo-white.svg',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'SOAFEE',
    description: 'Delivering a cloud-native architecture for mixed-criticality automotive applications.',
    repositoryURL: 'https://soafee.io/ ',
    documentationURL: '',
    img: 'soafee.svg',
  },
  {
    isEnable: true,
    tag: 'Finance',
    name: 'FINOS',
    description: 'Open source solutions for financial services',
    repositoryURL: 'https://www.finos.org/',
    documentationURL: '',
    img: 'finos-logo.png',
  },
  {
    isEnable: true,
    tag: 'Umbrella',
    name: 'Linux Foundation',
    description: 'Linux Foundation',
    repositoryURL: 'https://www.linuxfoundation.org/',
    documentationURL: '',
    img: 'LF_Logo_White.svg',
  },
  {
    isEnable: true,
    tag: 'Umbrella',
    name: 'GAIA-X',
    description: 'Gaia-X, initiated by Europe business politics, and science to create a federated and secure data infrastructure.',
    repositoryURL: 'https://gaia-x.eu/',
    documentationURL: '',
    img: 'Gaia-X_Logo_svg_resized_1.svg',
  },
  {
    isEnable: true,
    tag: 'Umbrella',
    name: 'Eclipse',
    description: 'Eclipse Foundation',
    repositoryURL: 'https:/eclipse.org',
    documentationURL: '',
    img: 'eclipse-foundation-logo-white.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Gnome Project',
    description: 'The Gnome Project',
    repositoryURL: 'https://www.gnome.org/',
    documentationURL: '',
    img: 'gnome-logo.png',
  },
  {
    isEnable: true,
    tag: 'Edge',
    name: 'Nephio',
    description: 'Cloud Native Network Automation',
    repositoryURL: 'https://nephio.org/',
    documentationURL: '',
    img: 'Nephio_logo_colorblack_horizontal.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'NVM Express',
    description: 'An open collection of standards and information to expose the benefits of non-volatile memory',
    repositoryURL: 'https://nvmexpress.org/',
    documentationURL: '',
    img: 'nvm-express-web.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'OpenACC',
    description: 'An open collection of standards and information to expose the benefits of non-volatile memory',
    repositoryURL: 'https://www.openacc.org/',
    documentationURL: '',
    img: 'openacc_logo.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'openHPC',
    description: 'Programming standard for parallel computing',
    repositoryURL: 'https://openhpc.community/',
    documentationURL: '',
    img: 'HPC3.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Open Mainframe Project',
    description: 'Host of open source projects for the mainframe.',
    repositoryURL: 'https://www.openmainframeproject.org/',
    documentationURL: '',
    img: 'logo_openmainframe.png',
  },
  {
    isEnable: false,
    tag: 'Infrastructure',
    name: 'openMP',
    description: 'API for multi-platform shared-memory parallel programming',
    repositoryURL: 'https://www.openmp.org/',
    documentationURL: '',
    img: 'openmp-header-logo-100h.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'openSSF',
    description: 'Open Source Security Foundation',
    repositoryURL: 'https://openssf.org/',
    documentationURL: '',
    img: 'openssf_white.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Open Source Business Alliance',
    description: 'Open Source Business Alliance developing, building and using open source software.',
    repositoryURL: 'https://osb-alliance.de/',
    documentationURL: '',
    img: 'osba-logo-claim.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'PCI-SIG',
    description: 'Peripheral Component Interconnect SIG responsible for specifying the PCI-X and PCI Express computer buses.',
    repositoryURL: 'https://pcisig.com/',
    documentationURL: '',
    img: 'pcisig.webp',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'RISC-V',
    description: 'An open standard collaboration for an open ISA',
    repositoryURL: 'https://riscv.org/',
    documentationURL: '',
    img: 'riscv-color.svg',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'UEFI',
    description: 'Unified Extensible Firmware Interface Forum',
    repositoryURL: 'https://uefi.org/',
    documentationURL: '',
    img: 'uefi_logo_red_web.png',
  },
  {
    isEnable: true,
    tag: 'Infrastructure',
    name: 'Zero Outage',
    description: 'Defining an industry standard for IT quality',
    repositoryURL: 'https://zero-outage.com/',
    documentationURL: '',
    img: 'ZOIS-logo.png',
  },
]
